language: minimal

services: docker

install:
  - ENV=dev make build
  - ENV=prod make build

script:
  - ENV=dev make start wait-healthy logs stop
  - ENV=prod make start wait-healthy logs stop
  - make lint test
